apiVersion: nuclio.io/v1beta1
kind: Function
metadata:
  name: soc-pipe-archive-processor
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    data: soc
spec:
  alias: latest
  description: Ingest a GeoTIFF archive and send each pixel as a GeoJSON feature in a Kafka topic
  handler: main:handler
  image: eufast/soc-pipe-archive-processor:0.1.0
  replicas: 1
  maxReplicas: 1
  runtime: python:3.6
  env:
  - name: KAFKA_BOOTSTRAP_SERVER
    value: "kafka-broker.kafka:9092"
  - name: TARGET_TOPIC
    value: soc-pipe
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 2
      memory: 4Gi
  triggers:
    kafka:
      kind: kafka
      attributes:
        topic: "soc-pipe-download"
        partitions: [0,1,2]
      url: "kafka-broker.kafka:9092"
  version: -1
status:
  state: waitingForResourceConfiguration
